# Generated by Django 4.1.7 on 2023-03-26 13:59

from django.db import migrations, models
import django.db.models.deletion
import menus.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок меню')),
                ('url', menus.utils.MyUrlField(help_text='Заменить на полную внешнюю ссылку при необходимости ( https://... или http://... )', max_length=200, unique=True, verbose_name='link or url name')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, help_text='Оставить пустым, если корневой', null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menuelements', verbose_name='Родительский пункт меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
